apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: ops
data:
  prometheus.yaml.tmpl: |
    global:
      scrape_interval: 15s
      scrape_timeout: 15s
      external_lables:
        cluster: ops-test
        replica: ${POD_NAME} # 每个 Prometheus 有一个唯一的标签
    rule_files:
    - /etc/prometheus/rules/*rules.yaml

    alerting:
      alert_relabel_configs: # 告警从不通的副本中去重
      - regex: replica 
        action: labeldrop
      alertmanagers:
      - scheme: http
        path_prefix: / 
        static_configs:
        - taggets: ['alertmanager:9093']  

